var GAME_LEVELS = [
  ["  x                                                                                                    x ",
   "  x                                                                                                    x ",
   "  x                                                                                                    x ",
   "  x                                                                                                    x ",
   "  x                                                                                                    x ",
   "  x                                                                                                    x ",
   "  x                                                                                                    x ",
   "  x                                                                                                f   x ",
   "  x                                                                                               fff  x ",
   "  x                                                                                               fff  x ",
   "  x                                                                                               fff  x ",
   "  x                         xx                                                                     f   x ",
   "  x                         xx                                                                     f   x ",
   "  x                o        xx                                                                     f   x ",
   "  x        o       x        xx                                             xxb                     f   x ",
   "  x        x      xxx     o xx                                 xxxxxxxxxxxxxxx           xxxxxxxxxxx   x ",
   "  x  @    xxx    xxxxx    b xx                              s                x!!!!!!!!!!!x             x ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxxx       xxxxxxxxxxxx           xxxxxxxxxxxxx             x ",
   "                                     x!!x     x!!!!!!!x          x                                   b x ",
   "                                     xxxx     xxxxxxxxx          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                        ",
   "                                                                                                        ",
   "                                                                                                        ",
   "                                                                                                        "],
  ["                                                                                               x        x",
   "                                                                                               x f      x",
   "                                                                                               xfff     x",
   "                                                                                               xfff     x",
   "                                                                                               xfff     x",
   "                                                                                               x f      x",
   "                                                                                               x f      x",
   "                                                                                               x f      x",
   "                                                                                               x f      x",
   "                                                                                       xxxxxxxxxxxxxx  bx",
   "                                                         x                                          x  bx",
   "                                                         xs                                         x  bx",
   "                                                         xxxxxxx                   b                x  bx",
   "                                                                   xxxxxxxxxxxxxxxxx                x  bx",
   "                                                                                                    x  bx",
   "                                                                                                    x  bx",
   "                                                                                                    x  bx",
   "                                                                                                    x  bx",
   "                                                                  b                                 x  bx",
   "                                            xxxxxxxxxxxxxxxxxxxxxxx                                 x  bx",
   "     @                                           x            x                                     x  bx",
   "    xxx      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  x            x                                     x  bx",
   "    x x      x                                x  x            x     b                               x  bx",
   "!!!!x x!!!!!!x                                x  x            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  bx",
   "!!!!x x!!!!!!x                                x  x            x              |                      x  bx",
   "!!!!x x!!!!!!x                                x  x            x       |             |               x  bx",
   "!!!!x x!!!!!!x                                x  x                x                           x     x  bx",
   "!!!!x x!!!!!!x                                x       x =         xx     !       !            x        bx",
   "!!!!x x!!!!!!x                                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!x x!!!!!!x                                                                                           "],
  ["  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  x         x                                          x                  x     s                 x           x",
   "  x         x                                          x                  x                       x           x",
   "  x         x                                          x                  x                       x           x",
   "  x         x                                          x                  x                       x           x",
   "  x         x                                          x                  x                       x           x",
   "  x         x                                          x                  x                       x           x",
   "  x         x                                          x                  x                       x           x",
   "  x         x                                          x                  x                       x           x",
   "  x         x                                          x                  x                       x           x",
   "  x         x                                          x                  x     b                 x           x",
   "  x         x                                          x                  x                       x           x",
   "  x         x                                          x                  x                       x           x",
   "  x         x                                          x                  x                       x           x",
   "  x         x                                          x                  x                       x           x",
   "  x         x                                          x                  x              b        x           x",
   "  x         x                                          x                  x                       x           x",
   "  x         x                                          x                  x                       x           x",
   "  x         x                                          x                  x                       x           x",
   "  x         x                                          x                  x                      bx           x",
   "  x @       x                                 xxxxxxx  x                  x                       x           x",
   "  xxxxx     x            xxxxx                x!!!!!x  x                  x                       x     f     x",
   "  x   x     x            x!!!x                x     x  x                  x                       x    fff    x",
   "  x   x     x             vvv                 x     x  x                  x                       x    fff    x",
   "  x   x     x                                bx     x  x                  x                       x    fff    x",
   "  x   x  o  x                                          x                  x                b      x     f     x",
   "  x   x          xxxxxx                                                                    xxxxxxxx     f     x",
   "  x   x          x!!!!x              xxxx                                                  x            f     x",
   "  x   x          x    x              x  x       bbb    x     =               =  x          x            f     x",
   "  x   xxxxxxxxxxxx    xxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      xxxxx                  x",
   "  x                    x o                                                           xxx                      x",
   "  x                        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                        x",
   "  x                        x                               v           v                                      x",
   "  x                        x                                                                  !               x",
   "  x   o  xxxxxxxxx    xxxxxx                                                                 !!!  bbbbbbbbbbbbx",
   "  x      x        bbbb          =      x                                       o  o  o      !!!!!             x",
   "  x      x                             x                                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  x      x                             x               x                                 x                     ",
   "  x      x                             x               x                                 x                     ",
   "  x      x                             x               x                                 x                     ",
   "  x      x                             x               x                                 x                     ",
   "  x      x                             x               x                                 x                     ",
   "  x      x                             x               x                                 x                     ",
   "  x      x                             x               x                                 x                     ",
   "  x      x                          b  x   b        b  x      b           b              x                     ",
   "  x      x                             x               x                                 x                     ",
   "  x      x                             x               x                                 x                     ",
   "  x      x                             x               x                                 x                     ",
   "  x      xxxxxxxxxxxxxxxxxxxxxxxxx     x                                                 x                     ",
   "  x                                    x !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                     ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                     ",
   "                                                                                                               ",
   "                                                                                                               "],
  ["                                                                                                              ",
   " x           x   x   x     x",
   " x           x   x   x     x",
   " x           x   x   x     x",
   " x           x   x   xx    x",
   " x           x   x   x x   x",
   " x           x   x   x x   x",
   " x           x   x   x x   x",
   " x     x     x   x   x  x  x",
   " x    xxx    x   x   x  x  x",
   " x   x   x   x   x   x   x x",
   "  x x     x x    x   x    xx",
   "   x       x     x   x     x",
   "                           ",]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
